@echo off
REM LSDAMM - Windows Auto Setup Script
REM Automated installation and configuration for Windows users

setlocal enabledelayedexpansion

echo =======================================
echo   LSDAMM Windows Auto Setup
echo   Lackadaisical Spectral Distributed AI MCP Mesh
echo =======================================
echo.

REM Colors (using Windows 10+ ANSI escape codes)
set "GREEN=[92m"
set "YELLOW=[93m"
set "RED=[91m"
set "NC=[0m"

REM Check if running as administrator
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo %RED%Warning: Not running as administrator%NC%
    echo Some features may require elevated privileges.
    echo.
    timeout /t 3 >nul
)

REM ===========================================
REM Step 1: Check Prerequisites
REM ===========================================
echo %YELLOW%[1/8] Checking prerequisites...%NC%
echo.

REM Check Node.js
where node >nul 2>&1
if %errorLevel% neq 0 (
    echo %RED%Error: Node.js is not installed%NC%
    echo.
    echo Please install Node.js 20+ from: https://nodejs.org/
    echo After installation, restart this script.
    pause
    exit /b 1
)

REM Check Node version
for /f "tokens=*" %%i in ('node -v') do set NODE_VERSION=%%i
echo   [OK] Node.js %NODE_VERSION% found
echo.

REM Check npm
where npm >nul 2>&1
if %errorLevel% neq 0 (
    echo %RED%Error: npm is not installed%NC%
    pause
    exit /b 1
)
echo   [OK] npm found
echo.

REM Check Git (optional but recommended)
where git >nul 2>&1
if %errorLevel% neq 0 (
    echo %YELLOW%Warning: Git is not installed (optional)%NC%
    echo   Git can be downloaded from: https://git-scm.com/
    echo.
) else (
    echo   [OK] Git found
    echo.
)

REM ===========================================
REM Step 2: Install Server Dependencies
REM ===========================================
echo %YELLOW%[2/8] Installing server dependencies...%NC%
echo.

cd server
if not exist "package.json" (
    echo %RED%Error: server/package.json not found%NC%
    echo   Make sure you're running this script from the LSDAMM root directory
    pause
    exit /b 1
)

call npm install
if %errorLevel% neq 0 (
    echo %RED%Error: Failed to install server dependencies%NC%
    pause
    exit /b 1
)
echo   [OK] Server dependencies installed
echo.

REM ===========================================
REM Step 3: Setup Directories
REM ===========================================
echo %YELLOW%[3/8] Creating required directories...%NC%
echo.

if not exist "data" mkdir data
if not exist "logs" mkdir logs
if not exist "data\uploads" mkdir data\uploads

echo   [OK] Directories created
echo.

REM ===========================================
REM Step 4: Configuration Files
REM ===========================================
echo %YELLOW%[4/8] Setting up configuration files...%NC%
echo.

REM Copy server.toml if not exists
if not exist "config\server.toml" (
    if exist "config\server.example.toml" (
        copy "config\server.example.toml" "config\server.toml" >nul
        echo   [OK] Created config\server.toml from template
    ) else (
        echo %YELLOW%   Warning: config\server.example.toml not found%NC%
    )
) else (
    echo   [OK] config\server.toml already exists
)

REM Create .env if not exists
if not exist ".env" (
    if exist "config\.env.example" (
        copy "config\.env.example" ".env" >nul
        echo   [OK] Created .env from template
        echo.
        echo   %YELLOW%IMPORTANT: Please edit .env and add your API keys:%NC%
        echo     - JWT_SECRET (generate a random string)
        echo     - OPENAI_API_KEY (if using OpenAI)
        echo     - ANTHROPIC_API_KEY (if using Anthropic/Claude)
        echo     - GOOGLE_API_KEY (if using Google Gemini)
        echo     - XAI_API_KEY (if using xAI Grok)
        echo.
    ) else (
        echo   %YELLOW%Creating basic .env file...%NC%
        (
            echo # LSDAMM Environment Configuration
            echo # Generated by setup.bat
            echo.
            echo # JWT Secret - CHANGE THIS TO A RANDOM STRING
            echo JWT_SECRET=change-this-to-a-secure-random-string
            echo.
            echo # API Keys - Add your keys here
            echo # OPENAI_API_KEY=sk-...
            echo # ANTHROPIC_API_KEY=sk-ant-...
            echo # GOOGLE_API_KEY=...
            echo # XAI_API_KEY=xai-...
            echo # OLLAMA_API_KEY=... (if using Ollama Cloud)
            echo.
            echo # Server Configuration
            echo PORT=3001
            echo HOST=0.0.0.0
            echo.
            echo # Database
            echo DB_PATH=./data/mesh.db
            echo.
            echo # Logging
            echo LOG_LEVEL=info
            echo LOG_FILE=./logs/server.log
        ) > .env
        echo   [OK] Created basic .env file
    )
) else (
    echo   [OK] .env already exists
)
echo.

REM ===========================================
REM Step 5: Build TypeScript
REM ===========================================
echo %YELLOW%[5/8] Building TypeScript...%NC%
echo.

call npm run build
if %errorLevel% neq 0 (
    echo %RED%Error: TypeScript build failed%NC%
    pause
    exit /b 1
)
echo   [OK] TypeScript build complete
echo.

REM ===========================================
REM Step 6: Initialize Database
REM ===========================================
echo %YELLOW%[6/8] Initializing database...%NC%
echo.

if exist "data\mesh.db" (
    echo   %YELLOW%Database already exists. Skipping initialization.%NC%
    echo   %YELLOW%To reinitialize, delete data\mesh.db and run this script again.%NC%
) else (
    call npm run setup:db
    if %errorLevel% neq 0 (
        echo %YELLOW%Warning: Database setup had issues (this may be normal)%NC%
    ) else (
        echo   [OK] Database initialized
    )
)
echo.

REM ===========================================
REM Step 7: Install Chatbot Dependencies (Optional)
REM ===========================================
echo %YELLOW%[7/8] Installing chatbot dependencies...%NC%
echo.

cd ..\chatbot
if exist "package.json" (
    call npm install
    if %errorLevel% equ 0 (
        echo   [OK] Chatbot dependencies installed
    ) else (
        echo   %YELLOW%Warning: Chatbot installation had issues%NC%
    )
) else (
    echo   %YELLOW%Chatbot package.json not found, skipping...%NC%
)
echo.

cd ..\server

REM ===========================================
REM Step 8: Create Startup Scripts
REM ===========================================
echo %YELLOW%[8/8] Creating startup scripts...%NC%
echo.

REM Create start-server.bat
(
    echo @echo off
    echo REM LSDAMM Server Startup Script
    echo cd server
    echo echo Starting LSDAMM Coordination Server...
    echo npm run dev
) > ..\start-server.bat

echo   [OK] Created start-server.bat

REM Create start-chatbot.bat
(
    echo @echo off
    echo REM LSDAMM Chatbot Startup Script
    echo cd chatbot
    echo echo Starting LSDAMM Chatbot...
    echo npm start
) > ..\start-chatbot.bat

echo   [OK] Created start-chatbot.bat

REM Create start-all.bat
(
    echo @echo off
    echo REM LSDAMM - Start All Services
    echo echo Starting LSDAMM Services...
    echo start "LSDAMM Server" cmd /k start-server.bat
    echo timeout /t 3 >nul
    echo start "LSDAMM Chatbot" cmd /k start-chatbot.bat
    echo echo.
    echo echo All services started!
    echo echo   - Server: http://localhost:3001
    echo echo   - Chatbot: http://localhost:8080
    echo echo.
) > ..\start-all.bat

echo   [OK] Created start-all.bat
echo.

cd ..

REM ===========================================
REM Setup Complete
REM ===========================================
echo.
echo %GREEN%=======================================
echo   Setup Complete!
echo =======================================%NC%
echo.
echo %GREEN%Next Steps:%NC%
echo.
echo   1. Edit server\.env with your API keys:
echo      - JWT_SECRET (required)
echo      - AI provider keys (OpenAI, Anthropic, etc.)
echo.
echo   2. (Optional) Edit server\config\server.toml for advanced settings
echo.
echo   3. Start the services:
echo      - Double-click start-all.bat to start everything
echo      - Or run start-server.bat and start-chatbot.bat separately
echo.
echo   4. Access the services:
echo      - Server API: http://localhost:3001
echo      - Chatbot UI: http://localhost:8080
echo      - Health Check: http://localhost:3001/api/health
echo.
echo %GREEN%Documentation:%NC%
echo   - README.md - General overview
echo   - docs/API.md - API documentation
echo   - LSDAMM-FULL-Scaffold-and-Build.md - Architecture guide
echo.
echo %YELLOW%Important Security Notes:%NC%
echo   - Change the JWT_SECRET in .env to a secure random string
echo   - Keep your API keys secure and never commit them to git
echo   - Use HTTPS in production deployments
echo.
echo Press any key to exit...
pause >nul
